### ISSUE TITLE
Case-2-8-4的运行结果与书上写的不一致，详情见下

### ISSUE THREAD

**Issue by toddlerya** [qitaos/rf-demos#1]
https://github.com/qitaos/rf-demos/blob/master/rf-book-case/test/Suite-2-8.robot
复制如下内容执行
Case-2-8-4
    @{argVal4}    Create List    abcd    WARN
    log    ${argVal4}
    ${argVal4}    Create List    1234    5678
    log    ${argVal4}
    ${listVal4}    Create List    1234    5678
    log    =@{listVal4}=
    log    =@{argVal4}=
    @{argVal4}    Create List    4444    8888
    log    ${argVal4}

![image](https://user-images.githubusercontent.com/5418150/39407434-a8a3a74c-4bf8-11e8-9d40-e4518ed88a66.png)

运行效果如下

![image](https://user-images.githubusercontent.com/5418150/39407447-c67be16c-4bf8-11e8-9f04-bd1367394e15.png)

麻烦解答下，是不是RF更新语法特性了？

**Comment by qitaos** [comment]
这个是因为Robotframework3.0（或者说2.9开始）这里已经改变了，其实在书中那一章最后一节有说这个事情。所以你检查一下你的RF版本是不是2.9以上了，如果是的话，你目前运行的结果是没问题的。书中例子是以2.8.7版本来介绍的。
